import type { Metadata } from "next";
import { Footer } from "@/components/Footer";

import "@fontsource-variable/playfair-display";
import "@fontsource-variable/quicksand";
import "./globals.css";
import Header from "@/components/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className="bg-mainBg">
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
